export const curves = {
  bonares: {
    label: "Bonares",
    symbols: [
      { display: "AL29", rofexTicker: "AL29" },
      { display: "AL29D", rofexTicker: "AL29D" },
      { display: "AL29C", rofexTicker: "AL29C" },
      { display: "AL30", rofexTicker: "AL30" },
      { display: "AL30D", rofexTicker: "AL30D" },
      { display: "AL30C", rofexTicker: "AL30C" },
      { display: "AL35", rofexTicker: "AL35" },
      { display: "AL35D", rofexTicker: "AL35D" },
      { display: "AL35C", rofexTicker: "AL35C" },
      { display: "AL41", rofexTicker: "AL41" },
      { display: "AL41D", rofexTicker: "AL41D" },
      { display: "AL41C", rofexTicker: "AL41C" },
    ],
  },
  globales: {
    label: "Globales",
    symbols: [
      { display: "GD29", rofexTicker: "GD29" },
      { display: "GD29D", rofexTicker: "GD29D" },
      { display: "GD29C", rofexTicker: "GD29C" },
      { display: "GD30", rofexTicker: "GD30" },
      { display: "GD30D", rofexTicker: "GD30D" },
      { display: "GD30C", rofexTicker: "GD30C" },
      { display: "GD35", rofexTicker: "GD35" },
      { display: "GD35D", rofexTicker: "GD35D" },
      { display: "GD35C", rofexTicker: "GD35C" },
      { display: "GD38", rofexTicker: "GD38" },
      { display: "GD38D", rofexTicker: "GD38D" },
      { display: "GD38C", rofexTicker: "GD38C" },
      { display: "GD41", rofexTicker: "GD41" },
      { display: "GD41D", rofexTicker: "GD41D" },
      { display: "GD41C", rofexTicker: "GD41C" },
      { display: "GD46", rofexTicker: "GD46" },
      { display: "GD46D", rofexTicker: "GD46D" },
      { display: "GD46C", rofexTicker: "GD46C" },
    ],
  },
  bopreales: {
    label: "Bopreales",
    symbols: [
      { display: "BPJ25", rofexTicker: "BPJ25" },
      { display: "BPY26", rofexTicker: "BPY26" },
      { display: "BPD27", rofexTicker: "BPD27" },
      { display: "BPOA7", rofexTicker: "BPOA7" },
      { display: "BPOB7", rofexTicker: "BPOB7" },
      { display: "BPOC7", rofexTicker: "BPOC7" },
    ],
  },
};
